title: 'Well hello and welcome to my life! This i what happened in my small corner of earth today:'
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.09291081
  brandStrength: 0
  lightness: 0.9779807
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  rhythmicContrast: 0.2432868
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Marcus Aurelius II
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.2422127
layout_spectrum: 0.74341
