name: Marcus Aurelius II
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2422127
title: 'Well hello and welcome to my life! This i what happened in my small corner of earth today:'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6875
  lightness: 0.9092373
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
